/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <system_stm32f4xx.h>
#include <stdint.h>
#include <stdlib.h>
#include <timer.h>
#include <time.h>
#include <ucglib.h>
#include <button.h>
#include <eventbutton.h>

#include <stdio.h>
#include <stdlib.h>

#include "boardconfig.h"
#include "drivers/gpio.h"
#include "drivers/timebase.h"
#include "periph/led.h"
#include "periph/buzzer.h"
#include "periph/button.h"
#include "graphic/display_init.h"
#include "game/menu_ui.h"
#include "game/run_game.h"

typedef enum {
    STATE_MENU,
    STATE_GAME
} GameState;


int main(void) {
	SystemCoreClockUpdate();
	TimerInit();
    GPIO_EnableAllClocks();
    LED_Init();
    Buzzer_Init();
    Button_Init();
    Display_Init();

    GameState state = STATE_MENU;

    ucg_ClearScreen(&ucg);

    while(1) {
        switch(state) {
            case STATE_MENU:
            	ucg_SetColor(&ucg, 0, 0, 0, 0);
            	ucg_DrawBox(&ucg, 0, 0, SCR_W, SCR_H);
                UI_ShowMenu();
                state = STATE_GAME;
                break;

            case STATE_GAME:
                run_game();
                ucg_SetColor(&ucg, 0, 0, 0, 0);
                ucg_DrawBox(&ucg, 0, 0, SCR_W, SCR_H);
                state = STATE_MENU;
                break;
        }
    }
}
